server:
  port: 3344

#连接远程仓库
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1287756283/springcloud-config.git
          default-label: main





