server:
  port: 80

#开启服务降低feign-hystrix
feign:
  hystrix:
    enabled: true

#Eureka的配置
eureka:
  client:
    register-with-eureka: false #不向eureka中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
